n1 = int(input("Digite um numero: "))
n2 = int(input("Digite outro numero: "))
n3 = int(input("Digite outro numero: "))
n4 = int(input("Digite outro numero: "))
soma = (n1 + n2+n3+n4)
produto = (n1*n2*n3*n4)
print(f'A soma dos números é: {soma}')
print(f"O produto dos números é: {produto}")